### ISSUE TITLE
setting from and to ignored when numcaps is 1

### ISSUE THREAD

**Issue by LelouBil** [mutschler/mt#22]
I don't know if this is a bug or if I'm just misusing mt but when I do this
`mt -n 1 -s RMGy2cMiDxoUGwmu9VfMG6.mp4 --to="00:00:00" --from "00:00:00"`
I expect to get the first frame of the video, but instead I get
```
INFO[0000] useing font: DroidSans.ttf
INFO[0000] generating contact sheet for RMGy2cMiDxoUGwmu9VfMG6.mp4
INFO[0000] First screenshot will be at 00:00:00
INFO[0000] Last screenshot will be at 00:00:00
INFO[0000] generating screenshot 01/01 at 00:01:04
```

The video is 00:01:04 long, so I get a black image

**Comment by mutschler** [comment]
currently `from` and `to` can't be the same value.
you'll need at least a one second difference between the two. 
try `mt -n 1 -s RMGy2cMiDxoUGwmu9VfMG6.mp4 --to="00:00:01" --from "00:00:00"`

**Comment by LelouBil** [comment]
okay then, but related issue : 

why does --to="00:00:00" only still does a screenshot at the end of the video ?
`mt -n 1 -s wdS8shRRnc7tgKZF4WCQRZ.mp4 --to="00:00:00"`
produces
```
INFO[0000] useing font: DroidSans.ttf
INFO[0000] generating contact sheet for wdS8shRRnc7tgKZF4WCQRZ.mp4
INFO[0000] Last screenshot will be at 00:00:00
INFO[0000] generating screenshot 01/01 at 00:01:27
```
This output does not make sense ?

**Comment by mutschler** [comment]
because the default value for `from` is `00:00:00` and you'll need at least a second of video to process...
there is currently no way to get the first screen of a video file with `mt` it's meant to be used for contactsheet generation or to give a general overview of the video.

as i mentioned above you could get a screen at `00:00:01` by passing `mt -n 1 -s wdS8shRRnc7tgKZF4WCQRZ.mp4 --to="00:00:01"` if you need to use the first frame you might want to use ffmpeg with something like this: `ffmpeg -i wdS8shRRnc7tgKZF4WCQRZ.mp4 -vframes 1 -s 480x300 -f image2 imagefile.jpg`

**Comment by mutschler** [comment]
@LelouBil with the latest push you should be able to do what you wanted to do the `from` and `to` options now support millisecond inputs as well so to generate a single screenshot at `00:00:00` try:

```
mt -n 1 -s wdS8shRRnc7tgKZF4WCQRZ.mp4 --to="00:00:00.1"
```

**Comment by LelouBil** [comment]
Thanks !
