### ISSUE TITLE
Start at 00:00:00 is ignored

### ISSUE THREAD

**Issue by benpollinger** [mutschler/mt#37]
Thanks for this @mutschler it's just what I needed.

I have 10 minute video clips that I'm using `--interval=30` but the first image is from (according to the timestamp) 00:00:30

I'd like it to start at 00:00:00 but adding `--from=00:00:00` does not seem to change anything.

Using `--numcaps=20` instead of interval doesn't seem to change it either.

Any suggestions? I'm using mt-1.0.11-arm-linux-gnueabihf.tar.gz

**Comment by mutschler** [comment]
you are right, currently there is no way to start at `00:00:00` the first image is grabbed at `00:00:00 + interval` this is kind of an design thing, since the default value for `--from` is `0` and it's only overwritten if `--from` is `> 0` so `--from=00:00:01` takes the first capture at `00:00:01` as it should.

Im not quite sure if i'd like to change the default behaviour to take the first cap always at `00:00:00` when i wrote this most files didn't have anything relevant in the first frame so that wasn't an issue... maybe that should be reconsidered.

PS: if you'd like to compile for yourself you could just remove the `if` statement here https://github.com/mutschler/mt/blob/master/mt.go#L158-L160 that should do the trick and always take the first image at `00:00:00`

**Comment by benpollinger** [comment]
Thanks for the quick reply. Yes, works OK if I specify `--from=00:00:01` and `--to=00:10:00` (otherwise it gives error about from>to)
